
package cn.movinginfo.tztf.webserviceClient.sms;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import cn.movinginfo.tztf.common.utils.ConfigWebserviceHelper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SendSMsgServiceService", targetNamespace = "http://cxf.SMsg.cn/", wsdlLocation = "http://localhost:8086/hyqxWebService/services/SMsg?wsdl")
public class SendSMsgServiceService
    extends Service
{

    private final static URL SENDSMSGSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SENDSMSGSERVICESERVICE_EXCEPTION;
    private final static QName SENDSMSGSERVICESERVICE_QNAME = new QName("http://cxf.SMsg.cn/", "SendSMsgServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	String value = ConfigWebserviceHelper.getValue("smsservice");
            url = new URL(value);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDSMSGSERVICESERVICE_WSDL_LOCATION = url;
        SENDSMSGSERVICESERVICE_EXCEPTION = e;
    }

    public SendSMsgServiceService() {
        super(__getWsdlLocation(), SENDSMSGSERVICESERVICE_QNAME);
    }

    public SendSMsgServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDSMSGSERVICESERVICE_QNAME, features);
    }

    public SendSMsgServiceService(URL wsdlLocation) {
        super(wsdlLocation, SENDSMSGSERVICESERVICE_QNAME);
    }

    public SendSMsgServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDSMSGSERVICESERVICE_QNAME, features);
    }

    public SendSMsgServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendSMsgServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendSMsgService
     */
    @WebEndpoint(name = "SendSMsgServicePort")
    public SendSMsgService getSendSMsgServicePort() {
        return super.getPort(new QName("http://cxf.SMsg.cn/", "SendSMsgServicePort"), SendSMsgService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendSMsgService
     */
    @WebEndpoint(name = "SendSMsgServicePort")
    public SendSMsgService getSendSMsgServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxf.SMsg.cn/", "SendSMsgServicePort"), SendSMsgService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDSMSGSERVICESERVICE_EXCEPTION!= null) {
            throw SENDSMSGSERVICESERVICE_EXCEPTION;
        }
        return SENDSMSGSERVICESERVICE_WSDL_LOCATION;
    }

}
