
package cn.movinginfo.tztf.webserviceClient.dingding;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DingDingService", targetNamespace = "http://cxf.dingding.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DingDingService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNameByUserIds", targetNamespace = "http://cxf.dingding.cn/", className = "cn.dingding.cxf.GetNameByUserIds")
    @ResponseWrapper(localName = "getNameByUserIdsResponse", targetNamespace = "http://cxf.dingding.cn/", className = "cn.dingding.cxf.GetNameByUserIdsResponse")
    public List<String> getNameByUserIds(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroupMembers", targetNamespace = "http://cxf.dingding.cn/", className = "cn.dingding.cxf.GetGroupMembers")
    @ResponseWrapper(localName = "getGroupMembersResponse", targetNamespace = "http://cxf.dingding.cn/", className = "cn.dingding.cxf.GetGroupMembersResponse")
    public List<String> getGroupMembers(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReadList", targetNamespace = "http://cxf.dingding.cn/", className = "cn.dingding.cxf.GetReadList")
    @ResponseWrapper(localName = "getReadListResponse", targetNamespace = "http://cxf.dingding.cn/", className = "cn.dingding.cxf.GetReadListResponse")
    public List<String> getReadList(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMsg", targetNamespace = "http://cxf.dingding.cn/", className = "cn.dingding.cxf.SendMsg")
    @ResponseWrapper(localName = "sendMsgResponse", targetNamespace = "http://cxf.dingding.cn/", className = "cn.dingding.cxf.SendMsgResponse")
    public String sendMsg(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUnReadList", targetNamespace = "http://cxf.dingding.cn/", className = "cn.dingding.cxf.GetUnReadList")
    @ResponseWrapper(localName = "getUnReadListResponse", targetNamespace = "http://cxf.dingding.cn/", className = "cn.dingding.cxf.GetUnReadListResponse")
    public List<String> getUnReadList(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getToken", targetNamespace = "http://cxf.dingding.cn/", className = "cn.dingding.cxf.GetToken")
    @ResponseWrapper(localName = "getTokenResponse", targetNamespace = "http://cxf.dingding.cn/", className = "cn.dingding.cxf.GetTokenResponse")
    public String getToken();

}
