<?xml version = "1.0" encoding = "UTF-8"?>
<alert xmlns = "http://com.icss.amp">
    <identifier>${identifier}</identifier>  
    <sender>${dept}</sender> 
    <senderCode>${senderCode}</senderCode>
    <phone></phone>
    <sendTime>${currentTime}+08:00</sendTime>
    <status>${status}</status>   
    <msgType>${msgType}</msgType>
    <scope>Public</scope> 
    <code>
        <method>
            <methodName>WEB</methodName>
            <message>${title!}</message>
            <audienceGrp>${audienceGrp!}</audienceGrp>
            <audenceprt>${audiencePrt!}</audenceprt>
        </method>
    </code>
    <secClassification>None</secClassification>
    <note>${title!}</note>
    <references>${reference!}</references>
    <info>
        <language>zh-CN</language>   
        <eventType>${eventType}</eventType>
        <urgency>Unknown</urgency>
        <severity>${color}</severity> 
        <certainty>Unknown</certainty>
        <effective>${publishTime}+08:00</effective>
        <onset>${onsetTime}+08:00</onset>
        <expires><#if expiresTime?exists>${expiresTime}+08:00</#if></expires>
        <senderName>${dept}</senderName>
        <headline>${title}</headline>
        <description>${desc}</description>
        <instruction>${defence}</instruction>
        <web></web> 
        <area>
            <areaDesc>${publishArea}</areaDesc> 
            <polygon/>
            <circle/>     
            <geocode>${publishAreaCode}</geocode>
        </area>
    </info>
</alert>