
package cn.movinginfo.tztf.webserviceClient.alarmFile;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import cn.movinginfo.tztf.common.utils.ConfigWebserviceHelper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CreateAlarmFileServiceService", targetNamespace = "http://cxf.alarmFile.cn/", wsdlLocation = "http://localhost:8086/hyqxWebService/services/CreateAlarmFile?wsdl")
public class CreateAlarmFileServiceService
    extends Service
{

    private final static URL CREATEALARMFILESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CREATEALARMFILESERVICESERVICE_EXCEPTION;
    private final static QName CREATEALARMFILESERVICESERVICE_QNAME = new QName("http://cxf.alarmFile.cn/", "CreateAlarmFileServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	String value = ConfigWebserviceHelper.getValue("alarmfile");
            url = new URL(value);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREATEALARMFILESERVICESERVICE_WSDL_LOCATION = url;
        CREATEALARMFILESERVICESERVICE_EXCEPTION = e;
    }

    public CreateAlarmFileServiceService() {
        super(__getWsdlLocation(), CREATEALARMFILESERVICESERVICE_QNAME);
    }

    public CreateAlarmFileServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREATEALARMFILESERVICESERVICE_QNAME, features);
    }

    public CreateAlarmFileServiceService(URL wsdlLocation) {
        super(wsdlLocation, CREATEALARMFILESERVICESERVICE_QNAME);
    }

    public CreateAlarmFileServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREATEALARMFILESERVICESERVICE_QNAME, features);
    }

    public CreateAlarmFileServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateAlarmFileServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreateAlarmFileService
     */
    @WebEndpoint(name = "CreateAlarmFileServicePort")
    public CreateAlarmFileService getCreateAlarmFileServicePort() {
        return super.getPort(new QName("http://cxf.alarmFile.cn/", "CreateAlarmFileServicePort"), CreateAlarmFileService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreateAlarmFileService
     */
    @WebEndpoint(name = "CreateAlarmFileServicePort")
    public CreateAlarmFileService getCreateAlarmFileServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxf.alarmFile.cn/", "CreateAlarmFileServicePort"), CreateAlarmFileService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREATEALARMFILESERVICESERVICE_EXCEPTION!= null) {
            throw CREATEALARMFILESERVICESERVICE_EXCEPTION;
        }
        return CREATEALARMFILESERVICESERVICE_WSDL_LOCATION;
    }

}
