
package cn.movinginfo.tztf.webserviceClient.weibo;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import cn.movinginfo.tztf.common.utils.ConfigWebserviceHelper;




/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WeiBoServiceService", targetNamespace = "http://service.cxf.weibo.cn/", wsdlLocation = "http://localhost:8086/hyqxWebService/services/weiboService?wsdl")
public class WeiBoServiceService
    extends Service
{

    private final static URL WEIBOSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException WEIBOSERVICESERVICE_EXCEPTION;
    private final static QName WEIBOSERVICESERVICE_QNAME = new QName("http://service.cxf.weibo.cn/", "WeiBoServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	String value = ConfigWebserviceHelper.getValue("sendweiboservice");
            url = new URL(value);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEIBOSERVICESERVICE_WSDL_LOCATION = url;
        WEIBOSERVICESERVICE_EXCEPTION = e;
    }

    public WeiBoServiceService() {
        super(__getWsdlLocation(), WEIBOSERVICESERVICE_QNAME);
    }

    public WeiBoServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEIBOSERVICESERVICE_QNAME, features);
    }

    public WeiBoServiceService(URL wsdlLocation) {
        super(wsdlLocation, WEIBOSERVICESERVICE_QNAME);
    }

    public WeiBoServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEIBOSERVICESERVICE_QNAME, features);
    }

    public WeiBoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeiBoServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeiBoService
     */
    @WebEndpoint(name = "WeiBoServicePort")
    public WeiBoService getWeiBoServicePort() {
        return super.getPort(new QName("http://service.cxf.weibo.cn/", "WeiBoServicePort"), WeiBoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeiBoService
     */
    @WebEndpoint(name = "WeiBoServicePort")
    public WeiBoService getWeiBoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cxf.weibo.cn/", "WeiBoServicePort"), WeiBoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEIBOSERVICESERVICE_EXCEPTION!= null) {
            throw WEIBOSERVICESERVICE_EXCEPTION;
        }
        return WEIBOSERVICESERVICE_WSDL_LOCATION;
    }

}
