
package cn.movinginfo.tztf.webserviceClient.fax;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendFaxService", targetNamespace = "http://cxf.fax.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendFaxService {


    /**
     * 
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @param arg3
     * @param arg17
     * @param arg2
     * @param arg18
     * @param arg5
     * @param arg4
     * @param arg13
     * @param arg14
     * @param arg1
     * @param arg15
     * @param arg0
     * @param arg16
     * @param arg10
     * @param arg11
     * @param arg12
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "upload", targetNamespace = "http://cxf.fax.cn/", className = "cn.movinginfo.tztf.webserviceClient.fax.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://cxf.fax.cn/", className = "cn.movinginfo.tztf.webserviceClient.fax.UploadResponse")
    public String upload(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        byte[] arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        byte[] arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        byte[] arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        byte[] arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        byte[] arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        byte[] arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        byte[] arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        byte[] arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        List<Object> arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        String arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        String arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        String arg15,
        @WebParam(name = "arg16", targetNamespace = "")
        String arg16,
        @WebParam(name = "arg17", targetNamespace = "")
        String arg17,
        @WebParam(name = "arg18", targetNamespace = "")
        String arg18);

}
