
package cn.movinginfo.tztf.webserviceClient.warnWeibo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WarnWeiBoServiceService", targetNamespace = "http://cxf.WarnWeibo.cn/", wsdlLocation = "http://localhost:8161/hyqxWebService/services/warnWeibo?wsdl")
public class WarnWeiBoServiceService
    extends Service
{

    private final static URL WARNWEIBOSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException WARNWEIBOSERVICESERVICE_EXCEPTION;
    private final static QName WARNWEIBOSERVICESERVICE_QNAME = new QName("http://cxf.WarnWeibo.cn/", "WarnWeiBoServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8161/hyqxWebService/services/warnWeibo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WARNWEIBOSERVICESERVICE_WSDL_LOCATION = url;
        WARNWEIBOSERVICESERVICE_EXCEPTION = e;
    }

    public WarnWeiBoServiceService() {
        super(__getWsdlLocation(), WARNWEIBOSERVICESERVICE_QNAME);
    }

    public WarnWeiBoServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WARNWEIBOSERVICESERVICE_QNAME, features);
    }

    public WarnWeiBoServiceService(URL wsdlLocation) {
        super(wsdlLocation, WARNWEIBOSERVICESERVICE_QNAME);
    }

    public WarnWeiBoServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WARNWEIBOSERVICESERVICE_QNAME, features);
    }

    public WarnWeiBoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WarnWeiBoServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WarnWeiBoService
     */
    @WebEndpoint(name = "WarnWeiBoServicePort")
    public WarnWeiBoService getWarnWeiBoServicePort() {
        return super.getPort(new QName("http://cxf.WarnWeibo.cn/", "WarnWeiBoServicePort"), WarnWeiBoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WarnWeiBoService
     */
    @WebEndpoint(name = "WarnWeiBoServicePort")
    public WarnWeiBoService getWarnWeiBoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxf.WarnWeibo.cn/", "WarnWeiBoServicePort"), WarnWeiBoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WARNWEIBOSERVICESERVICE_EXCEPTION!= null) {
            throw WARNWEIBOSERVICESERVICE_EXCEPTION;
        }
        return WARNWEIBOSERVICESERVICE_WSDL_LOCATION;
    }

}
