
package cn.movinginfo.tztf.webserviceClient.alarmFile;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreateAlarmFileService", targetNamespace = "http://cxf.alarmFile.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreateAlarmFileService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAlarmFile", targetNamespace = "http://cxf.alarmFile.cn/", className = "cn.movinginfo.tztf.webserviceClient.alarmFile.CreateAlarmFile")
    @ResponseWrapper(localName = "createAlarmFileResponse", targetNamespace = "http://cxf.alarmFile.cn/", className = "cn.movinginfo.tztf.webserviceClient.alarmFile.CreateAlarmFileResponse")
    public int createAlarmFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
