
package cn.movinginfo.tztf.webserviceClient.fax;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import cn.movinginfo.tztf.common.utils.ConfigWebserviceHelper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SendFaxServiceService", targetNamespace = "http://cxf.fax.cn/", wsdlLocation = "http://localhost:8086/hyqxWebService/services/SendFaxService?wsdl")
public class SendFaxServiceService
    extends Service
{

    private final static URL SENDFAXSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SENDFAXSERVICESERVICE_EXCEPTION;
    private final static QName SENDFAXSERVICESERVICE_QNAME = new QName("http://cxf.fax.cn/", "SendFaxServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	String value = ConfigWebserviceHelper.getValue("faxservice");
            url = new URL(value);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDFAXSERVICESERVICE_WSDL_LOCATION = url;
        SENDFAXSERVICESERVICE_EXCEPTION = e;
    }

    public SendFaxServiceService() {
        super(__getWsdlLocation(), SENDFAXSERVICESERVICE_QNAME);
    }

    public SendFaxServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDFAXSERVICESERVICE_QNAME, features);
    }

    public SendFaxServiceService(URL wsdlLocation) {
        super(wsdlLocation, SENDFAXSERVICESERVICE_QNAME);
    }

    public SendFaxServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDFAXSERVICESERVICE_QNAME, features);
    }

    public SendFaxServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendFaxServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendFaxService
     */
    @WebEndpoint(name = "SendFaxServicePort")
    public SendFaxService getSendFaxServicePort() {
        return super.getPort(new QName("http://cxf.fax.cn/", "SendFaxServicePort"), SendFaxService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendFaxService
     */
    @WebEndpoint(name = "SendFaxServicePort")
    public SendFaxService getSendFaxServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxf.fax.cn/", "SendFaxServicePort"), SendFaxService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDFAXSERVICESERVICE_EXCEPTION!= null) {
            throw SENDFAXSERVICESERVICE_EXCEPTION;
        }
        return SENDFAXSERVICESERVICE_WSDL_LOCATION;
    }

}
