
package cn.movinginfo.tztf.webserviceClient.getXml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceSoap {


    /**
     * 
     * @param micaps3
     * @param title
     * @param rainbowContent
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetM4Xml", action = "http://tempuri.org/GetM4Xml")
    @WebResult(name = "GetM4XmlResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetM4Xml", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetM4Xml")
    @ResponseWrapper(localName = "GetM4XmlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetM4XmlResponse")
    public String getM4Xml(
        @WebParam(name = "title", targetNamespace = "http://tempuri.org/")
        String title,
        @WebParam(name = "micaps3", targetNamespace = "http://tempuri.org/")
        String micaps3,
        @WebParam(name = "rainbowContent", targetNamespace = "http://tempuri.org/")
        String rainbowContent);

    /**
     * 
     * @param micaps4
     * @param title
     * @param rainbowContent
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetM4XmlByM4", action = "http://tempuri.org/GetM4XmlByM4")
    @WebResult(name = "GetM4XmlByM4Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetM4XmlByM4", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetM4XmlByM4")
    @ResponseWrapper(localName = "GetM4XmlByM4Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetM4XmlByM4Response")
    public String getM4XmlByM4(
        @WebParam(name = "title", targetNamespace = "http://tempuri.org/")
        String title,
        @WebParam(name = "micaps4", targetNamespace = "http://tempuri.org/")
        String micaps4,
        @WebParam(name = "rainbowContent", targetNamespace = "http://tempuri.org/")
        String rainbowContent);

    /**
     * 
     * @param datas
     * @param title
     * @param rainbowContent
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetM4Image", action = "http://tempuri.org/GetM4Image")
    @WebResult(name = "GetM4ImageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetM4Image", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetM4Image")
    @ResponseWrapper(localName = "GetM4ImageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetM4ImageResponse")
    public byte[] getM4Image(
        @WebParam(name = "title", targetNamespace = "http://tempuri.org/")
        String title,
        @WebParam(name = "datas", targetNamespace = "http://tempuri.org/")
        String datas,
        @WebParam(name = "rainbowContent", targetNamespace = "http://tempuri.org/")
        String rainbowContent);

    /**
     * 
     * @param datas
     * @param imagePath
     * @param title
     * @param rainbowContent
     * @param xmlPath
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CreateM4XmlAndImage", action = "http://tempuri.org/CreateM4XmlAndImage")
    @WebResult(name = "CreateM4XmlAndImageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateM4XmlAndImage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateM4XmlAndImage")
    @ResponseWrapper(localName = "CreateM4XmlAndImageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateM4XmlAndImageResponse")
    public boolean createM4XmlAndImage(
        @WebParam(name = "title", targetNamespace = "http://tempuri.org/")
        String title,
        @WebParam(name = "datas", targetNamespace = "http://tempuri.org/")
        String datas,
        @WebParam(name = "rainbowContent", targetNamespace = "http://tempuri.org/")
        String rainbowContent,
        @WebParam(name = "xmlPath", targetNamespace = "http://tempuri.org/")
        String xmlPath,
        @WebParam(name = "imagePath", targetNamespace = "http://tempuri.org/")
        String imagePath);

}
